name: Mac_dbl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyterlab
  - ca-certificates
  - openssl
  - pytorch
  - tqdm
  - ipywidgets
  - git
  - pip
  - pip:
    - pettingzoo[mpe]
    - git+https://github.com/sarah-keren/ai_dm
    - git+https://github.com/CLAIR-LAB-TECHNION/multi-taxi@0.4.0
    - git+https://github.com/sarah-keren/MAC
    - stable-baselines3
    - numpy==1.23.4
    - Pillow
    - matplotlib
    - pandas
